sonar.projectKey=meditracker
sonar.projectName=MediTracker mHealth
sonar.projectVersion=1.0
sonar.sources=.
sonar.language=py
sonar.python.version=3
sonar.exclusions=**/static/**,**/templates/**,**/wireframes/**,**/*.md,**/node_modules/**
sonar.host.url=http://sonarqube:9000